### ISSUE TITLE
Sizzling Stats Not Working

### ISSUE THREAD

**Issue by TheRealGDEabarod** [SizzlingStats/sizzlingplugins#29]
I just installed Sizzling Stats, and it is not working
I am playing on a dedicated server on my own IP, and I am using other plugins like logs.tf, medicstats, supstats and log_upload, and these are also not working.
I am using Windows, and my server.cfg looks like [this]( https://docs.google.com/document/d/1pXVyep5R4yyTO6KPPjRUIDbUSDQUkCnTfHYKHYZf6hI/edit?usp=sharing)
and my sizzlingstats.cfg looks like [this](https://docs.google.com/document/d/1Qsvx1bWKnwlCpqHq-e_TJLl5HuBMvtdboWiUpRfLjXY/edit?usp=sharing)

Help!

**Comment by SizzlingCalamari** [comment]
If other plugins also aren't working, they are probably not installed correctly. Double check file paths and follow the installation instructions again.

**Comment by TheRealGDEabarod** [comment]
They are installed correctly, and when I do "rcon sm plugins list", they say they are installed correctly, however, even when I finish a match, when I do !log or .ss, it says there are no stats available

**Comment by SizzlingCalamari** [comment]
The problem was a server configuration error.
mp_tournament 1 was not set in the server config.
